services:
  mc_heavy:
    image: glitchless/gli_mc_heavy:3
    ports:
      - "25567:25565"
    environment:
      MC_RAM: "16G"
    volumes:
      - ./world:/app/world
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./config/telegrambridge.toml:/app/config/telegrambridge.toml
